<a href="https://colab.research.google.com/github/GabriVini/DataMining/blob/main/Fish_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Load libraries

from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler

import pandas as pd
import numpy as np   

# Load the dataset
url = 'https://raw.githubusercontent.com/VitaT/ML-python/main/data/fish.csv'
data = pd.read_csv(url)
fish_y = np.array(data["Species"])

fish_x = data.drop("Species", axis = 1)

print(data)

    Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
142   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
143   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
144   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
145   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
146   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[147 rows x 7 columns]


In [ ]:
# Create standardizer
standardizer = StandardScaler()
# Standardize features
features_standardized = standardizer.fit_transform(fish_x)
# Two nearest neighbors
nearest_neighbors = NearestNeighbors(n_neighbors=2).fit(features_standardized)
# Create an observation
new_observation = [ 1, 1, 1, 1, 1, 1]
# Find distances and indices of the observation's nearest neighbors
distances, indices = nearest_neighbors.kneighbors([new_observation])


# View the nearest neighbors
features_standardized[indices]

print(indices)

print(features_standardized[indices])
print(distances)

[[113 108]]
[[[1.14739821 1.0591973  1.05512355 0.95137206 0.5183887  1.29667328]
  [0.6789653  0.99970093 0.9625357  0.85710927 0.51876863 0.92372589]]]
[[0.59211343 0.60190204]]


In [ ]:
# Find two nearest neighbors based on euclidean distance
nearestneighbors_euclidean = NearestNeighbors(
n_neighbors=2, metric='euclidean').fit(features_standardized)

In [ ]:
# View distances
distances

array([[0.59211343, 0.60190204]])

In [ ]:
# Find each observation's three nearest neighbors
# based on euclidean distance (including itself)
nearestneighbors_euclidean = NearestNeighbors(n_neighbors=3, metric="euclidean").fit(features_standardized)
# List of lists indicating each observation's 3 nearest neighbors
# (including itself)
nearest_neighbors_with_self = nearestneighbors_euclidean.kneighbors_graph(features_standardized).toarray()
# Remove 1's marking an observation is a nearest neighbor to itself
for i, x in enumerate(nearest_neighbors_with_self):
  x[i] = 0
# View first observation's two nearest neighbors
nearest_neighbors_with_self[0]
print(nearest_neighbors_with_self[0])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0.]


In [ ]:
# Load libraries
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np 

# Load data
url = 'https://raw.githubusercontent.com/VitaT/ML-python/main/data/fish.csv'
data = pd.read_csv(url)
fish_y = np.array(data["Species"])

fish_x = data.drop("Species", axis = 1)

# Create standardizer
standardizer = StandardScaler()
# Standardize features
X_std = standardizer.fit_transform(fish_x)
# Train a KNN classifier with 5 neighbors
knn = KNeighborsClassifier(n_neighbors=5, n_jobs=-1).fit(X_std, fish_y)
# Create two observations
new_observations = [[ 0.75, 0.75, 0.75, 0.75, 0.75, 0.75],
[ 1, 1, 1, 1, 1, 1]]
# Predict the class of two observations
knn.predict(new_observations)

array(['Perch', 'Perch'], dtype=object)

In [ ]:
# View probability each observation is one of three classes
knn.predict_proba(new_observations)

array([[0.2, 0. , 0.6, 0. , 0. , 0. , 0.2],
       [0. , 0. , 0.6, 0. , 0. , 0. , 0.4]])

In [ ]:
# Load libraries
from sklearn.neighbors import KNeighborsClassifier

from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.model_selection import GridSearchCV
import pandas as pd
import numpy as np 
# Load data
url = 'https://raw.githubusercontent.com/VitaT/ML-python/main/data/fish.csv'
data = pd.read_csv(url)
fish_y = np.array(data["Species"])
fish_x = data.drop("Species", axis = 1)
# Create standardizer
standardizer = StandardScaler()
# Create a KNN classifier
knn = KNeighborsClassifier(n_neighbors=5, n_jobs=-1)
# Create a pipeline
pipe = Pipeline([("standardizer", standardizer), ("knn", knn)])
# Create space of candidate values
search_space = [{"knn__n_neighbors": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]}]
# Create grid search
classifier = GridSearchCV(
pipe, search_space, cv=5, verbose=0).fit(fish_x, fish_y)

In [ ]:
# Best neighborhood size (k)
classifier.best_estimator_.get_params()["knn__n_neighbors"]

2